language: node_js
node_js:
  - "6.0"
env:
  global:
    secure: "mYlUsHv7pzzkTR67Bb75+AiP/IqT4VyUpmRYO672VJecxQW1whyhsSDY6ztFTRewXE6VilTRxlQ3m/ribg9e+9a9Rn1Keu//ctqf8m4xL4OVkBBLfebS68yuSzFg4ub/wNAB5fO4xhZYdNysbSJcSr2aXUzwWZgiLWMBXTvoKj6ETUtUBbToo5+eAQRlU0uT2kNvhhoLmlAWnVQgUYp5/KCbJK0qK+ehd/bN/BGZXTsCLW9uBf6Z4HuyHEXkdIBaNGb6weB11ARNhcGaHcWjmWM9ZlALyWRZYELGelIwsFTtsWfvD6p89yof3sklqHUkHdHgR2I7NN1jPuL3GcSAEOXY9NHIfqD6g1CFCo26NPhpDPcdb/sK2P0jK+npRLWUyOAtx4kvkllv1zOT/fknLKoj1EIlvdprGU8/DoWhjjCn5XL/rZO28mWGBlfZs1qeFoaRPI651N7JMROgXwHU3BaSnygb4kNizBqdQuaYZT4cth6hbcVV1f7ZLl9jzncHK0SC1VlX5qnVz6kZ5RbLX63Ive3iPJIU1r0rZlvzUsUO05jn0jdA+1AVuX4AUXd22l2u5ACwsXaj+Mcblr552GyH2AT2Cis+mSGYkSVZqOz5xT6x2DhDRwygfnpv2gGUGhLi4LFLsjwLJD023qb8lJTayNRVYcTynx6PBk1FAPo="
cache:
  directories:
  - $HOME/calibre-bin
sudo: false
before_script:
  - export PATH=$PATH:$HOME/calibre-bin/calibre
  - >
    which calibre ||
    wget -nv -O- https://raw.githubusercontent.com/kovidgoyal/calibre/master/setup/linux-installer.py |
    python -c "import sys; main=lambda x,y:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main('~/calibre-bin', True)"
script:
  - cd gitbook/
  - npm i
  - npm run archive
  - cd ../
after_success:
  - ./.ci/update-gh-pages.sh > /dev/null 2>&1
notifications:
  email:
    on_success: never
    on_failure: never
